//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.06 at 08:59:15 AM PDT 
//


package com.ibm.iot.cpntools.base;

import java.util.ArrayList;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cpntools.dtd}id"/>
 *         &lt;element ref="{cpntools.dtd}declare" minOccurs="0"/>
 *         &lt;element ref="{cpntools.dtd}timed" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{cpntools.dtd}unit"/>
 *           &lt;element ref="{cpntools.dtd}bool"/>
 *           &lt;element ref="{cpntools.dtd}int"/>
 *           &lt;element ref="{cpntools.dtd}real"/>
 *           &lt;element ref="{cpntools.dtd}string"/>
 *           &lt;element ref="{cpntools.dtd}enum"/>
 *           &lt;element ref="{cpntools.dtd}index"/>
 *           &lt;element ref="{cpntools.dtd}product"/>
 *           &lt;element ref="{cpntools.dtd}record"/>
 *           &lt;element ref="{cpntools.dtd}list"/>
 *           &lt;element ref="{cpntools.dtd}union"/>
 *           &lt;element ref="{cpntools.dtd}alias"/>
 *           &lt;element ref="{cpntools.dtd}subset"/>
 *         &lt;/choice>
 *         &lt;element ref="{cpntools.dtd}layout" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "declare",
    "timed",
    "unitOrBoolOrInt",
    "layout"
})
@XmlRootElement(name = "color")
public class Color {

    @XmlElement(required = true)
    protected java.lang.String id;
    protected Declare declare;
    protected Timed timed;
    @XmlElements({
        @XmlElement(name = "unit", type = Unit.class),
        @XmlElement(name = "bool", type = Bool.class),
        @XmlElement(name = "int", type = Int.class),
        @XmlElement(name = "real", type = Real.class),
        @XmlElement(name = "string", type = com.ibm.iot.cpntools.base.String.class),
        @XmlElement(name = "enum", type = Enum.class),
        @XmlElement(name = "index", type = Index.class),
        @XmlElement(name = "product", type = Product.class),
        @XmlElement(name = "record", type = Record.class),
        @XmlElement(name = "list", type = com.ibm.iot.cpntools.base.List.class),
        @XmlElement(name = "union", type = Union.class),
        @XmlElement(name = "alias", type = Alias.class),
        @XmlElement(name = "subset", type = Subset.class)
    })
    protected java.util.List<Object> unitOrBoolOrInt;
    protected java.lang.String layout;
    @XmlAttribute(name = "id")
    protected java.lang.String idColorAttr;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

    /**
     * Gets the value of the declare property.
     * 
     * @return
     *     possible object is
     *     {@link Declare }
     *     
     */
    public Declare getDeclare() {
        return declare;
    }

    /**
     * Sets the value of the declare property.
     * 
     * @param value
     *     allowed object is
     *     {@link Declare }
     *     
     */
    public void setDeclare(Declare value) {
        this.declare = value;
    }

    /**
     * Gets the value of the timed property.
     * 
     * @return
     *     possible object is
     *     {@link Timed }
     *     
     */
    public Timed getTimed() {
        return timed;
    }

    /**
     * Sets the value of the timed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timed }
     *     
     */
    public void setTimed(Timed value) {
        this.timed = value;
    }

    /**
     * Gets the value of the unitOrBoolOrInt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unitOrBoolOrInt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnitOrBoolOrInt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Unit }
     * {@link Bool }
     * {@link Int }
     * {@link Real }
     * {@link com.ibm.iot.cpntools.base.String }
     * {@link Enum }
     * {@link Index }
     * {@link Product }
     * {@link Record }
     * {@link com.ibm.iot.cpntools.base.List }
     * {@link Union }
     * {@link Alias }
     * {@link Subset }
     * 
     * 
     */
    public java.util.List<Object> getUnitOrBoolOrInt() {
        if (unitOrBoolOrInt == null) {
            unitOrBoolOrInt = new ArrayList<Object>();
        }
        return this.unitOrBoolOrInt;
    }

    /**
     * Gets the value of the layout property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getLayout() {
        return layout;
    }

    /**
     * Sets the value of the layout property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setLayout(java.lang.String value) {
        this.layout = value;
    }

    /**
     * Gets the value of the idColorAttr property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getIdColorAttr() {
        return idColorAttr;
    }

    /**
     * Sets the value of the idColorAttr property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setIdColorAttr(java.lang.String value) {
        this.idColorAttr = value;
    }

}
