//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.06 at 08:59:15 AM PDT 
//


package com.ibm.iot.cpntools.base;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cpntools.dtd}globbox"/>
 *         &lt;element ref="{cpntools.dtd}page" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{cpntools.dtd}fusion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{cpntools.dtd}instances"/>
 *         &lt;element ref="{cpntools.dtd}options"/>
 *         &lt;element ref="{cpntools.dtd}binders"/>
 *         &lt;element ref="{cpntools.dtd}monitorblock"/>
 *         &lt;element ref="{cpntools.dtd}IndexNode"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globbox",
    "page",
    "fusion",
    "instances",
    "options",
    "binders",
    "monitorblock",
    "indexNode"
})
@XmlRootElement(name = "cpnet")
public class Cpnet {

    @XmlElement(required = true)
    protected Globbox globbox;
    protected List<Page> page;
    protected List<Fusion> fusion;
    @XmlElement(required = true)
    protected Instances instances;
    @XmlElement(required = true)
    protected Options options;
    @XmlElement(required = true)
    protected Binders binders;
    @XmlElement(required = true)
    protected Monitorblock monitorblock;
    @XmlElement(name = "IndexNode", required = true)
    protected IndexNode indexNode;

    /**
     * Gets the value of the globbox property.
     * 
     * @return
     *     possible object is
     *     {@link Globbox }
     *     
     */
    public Globbox getGlobbox() {
        return globbox;
    }

    /**
     * Sets the value of the globbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link Globbox }
     *     
     */
    public void setGlobbox(Globbox value) {
        this.globbox = value;
    }

    /**
     * Gets the value of the page property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the page property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Page }
     * 
     * 
     */
    public List<Page> getPage() {
        if (page == null) {
            page = new ArrayList<Page>();
        }
        return this.page;
    }

    /**
     * Gets the value of the fusion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fusion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFusion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Fusion }
     * 
     * 
     */
    public List<Fusion> getFusion() {
        if (fusion == null) {
            fusion = new ArrayList<Fusion>();
        }
        return this.fusion;
    }

    /**
     * Gets the value of the instances property.
     * 
     * @return
     *     possible object is
     *     {@link Instances }
     *     
     */
    public Instances getInstances() {
        return instances;
    }

    /**
     * Sets the value of the instances property.
     * 
     * @param value
     *     allowed object is
     *     {@link Instances }
     *     
     */
    public void setInstances(Instances value) {
        this.instances = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link Options }
     *     
     */
    public Options getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link Options }
     *     
     */
    public void setOptions(Options value) {
        this.options = value;
    }

    /**
     * Gets the value of the binders property.
     * 
     * @return
     *     possible object is
     *     {@link Binders }
     *     
     */
    public Binders getBinders() {
        return binders;
    }

    /**
     * Sets the value of the binders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Binders }
     *     
     */
    public void setBinders(Binders value) {
        this.binders = value;
    }

    /**
     * Gets the value of the monitorblock property.
     * 
     * @return
     *     possible object is
     *     {@link Monitorblock }
     *     
     */
    public Monitorblock getMonitorblock() {
        return monitorblock;
    }

    /**
     * Sets the value of the monitorblock property.
     * 
     * @param value
     *     allowed object is
     *     {@link Monitorblock }
     *     
     */
    public void setMonitorblock(Monitorblock value) {
        this.monitorblock = value;
    }

    /**
     * Gets the value of the indexNode property.
     * 
     * @return
     *     possible object is
     *     {@link IndexNode }
     *     
     */
    public IndexNode getIndexNode() {
        return indexNode;
    }

    /**
     * Sets the value of the indexNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexNode }
     *     
     */
    public void setIndexNode(IndexNode value) {
        this.indexNode = value;
    }

}
