//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.06 at 08:59:15 AM PDT 
//


package com.ibm.iot.cpntools.base;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cpntools.dtd}pageattr"/>
 *         &lt;element ref="{cpntools.dtd}trans" maxOccurs="unbounded"/>
 *         &lt;element ref="{cpntools.dtd}place" maxOccurs="unbounded"/>
 *         &lt;element ref="{cpntools.dtd}arc" maxOccurs="unbounded"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{cpntools.dtd}Aux"/>
 *           &lt;element ref="{cpntools.dtd}vguideline"/>
 *           &lt;element ref="{cpntools.dtd}hguideline"/>
 *           &lt;element ref="{cpntools.dtd}group"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pageattr",
    "trans",
    "place",
    "arc",
    "auxOrVguidelineOrHguideline"
})
@XmlRootElement(name = "page")
public class Page {

    @XmlElement(required = true)
    protected Pageattr pageattr;
    @XmlElement(required = true)
    protected List<Trans> trans;
    @XmlElement(required = true)
    protected List<Place> place;
    @XmlElement(required = true)
    protected List<Arc> arc;
    @XmlElements({
        @XmlElement(name = "Aux", type = Aux.class),
        @XmlElement(name = "vguideline", type = Vguideline.class),
        @XmlElement(name = "hguideline", type = Hguideline.class),
        @XmlElement(name = "group", type = Group.class)
    })
    protected List<Object> auxOrVguidelineOrHguideline;
    @XmlAttribute(name = "id")
    protected java.lang.String id;

    /**
     * Gets the value of the pageattr property.
     * 
     * @return
     *     possible object is
     *     {@link Pageattr }
     *     
     */
    public Pageattr getPageattr() {
        return pageattr;
    }

    /**
     * Sets the value of the pageattr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pageattr }
     *     
     */
    public void setPageattr(Pageattr value) {
        this.pageattr = value;
    }

    /**
     * Gets the value of the trans property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trans property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrans().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Trans }
     * 
     * 
     */
    public List<Trans> getTrans() {
        if (trans == null) {
            trans = new ArrayList<Trans>();
        }
        return this.trans;
    }

    /**
     * Gets the value of the place property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the place property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Place }
     * 
     * 
     */
    public List<Place> getPlace() {
        if (place == null) {
            place = new ArrayList<Place>();
        }
        return this.place;
    }

    /**
     * Gets the value of the arc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Arc }
     * 
     * 
     */
    public List<Arc> getArc() {
        if (arc == null) {
            arc = new ArrayList<Arc>();
        }
        return this.arc;
    }

    /**
     * Gets the value of the auxOrVguidelineOrHguideline property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the auxOrVguidelineOrHguideline property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuxOrVguidelineOrHguideline().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Aux }
     * {@link Vguideline }
     * {@link Hguideline }
     * {@link Group }
     * 
     * 
     */
    public List<Object> getAuxOrVguidelineOrHguideline() {
        if (auxOrVguidelineOrHguideline == null) {
            auxOrVguidelineOrHguideline = new ArrayList<Object>();
        }
        return this.auxOrVguidelineOrHguideline;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
