//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.06 at 08:59:15 AM PDT 
//


package com.ibm.iot.cpntools.base;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cpntools.dtd}subpageinfo" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="subpage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="portsock" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subpageinfo"
})
@XmlRootElement(name = "subst")
public class Subst {

    protected Subpageinfo subpageinfo;
    @XmlAttribute(name = "subpage")
    protected java.lang.String subpage;
    @XmlAttribute(name = "portsock")
    protected java.lang.String portsock;

    /**
     * Gets the value of the subpageinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Subpageinfo }
     *     
     */
    public Subpageinfo getSubpageinfo() {
        return subpageinfo;
    }

    /**
     * Sets the value of the subpageinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subpageinfo }
     *     
     */
    public void setSubpageinfo(Subpageinfo value) {
        this.subpageinfo = value;
    }

    /**
     * Gets the value of the subpage property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSubpage() {
        return subpage;
    }

    /**
     * Sets the value of the subpage property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSubpage(java.lang.String value) {
        this.subpage = value;
    }

    /**
     * Gets the value of the portsock property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPortsock() {
        return portsock;
    }

    /**
     * Sets the value of the portsock property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPortsock(java.lang.String value) {
        this.portsock = value;
    }

}
