//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.06 at 08:59:15 AM PDT 
//


package com.ibm.iot.cpntools.base;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cpntools.dtd}zorder" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="panx" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pany" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="zoom" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="decl" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zorder"
})
@XmlRootElement(name = "textsheet")
public class Textsheet {

    protected Zorder zorder;
    @XmlAttribute(name = "id")
    protected java.lang.String id;
    @XmlAttribute(name = "panx")
    protected java.lang.String panx;
    @XmlAttribute(name = "pany")
    protected java.lang.String pany;
    @XmlAttribute(name = "zoom")
    protected java.lang.String zoom;
    @XmlAttribute(name = "decl", required = true)
    protected java.lang.String decl;

    /**
     * Gets the value of the zorder property.
     * 
     * @return
     *     possible object is
     *     {@link Zorder }
     *     
     */
    public Zorder getZorder() {
        return zorder;
    }

    /**
     * Sets the value of the zorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zorder }
     *     
     */
    public void setZorder(Zorder value) {
        this.zorder = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

    /**
     * Gets the value of the panx property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPanx() {
        return panx;
    }

    /**
     * Sets the value of the panx property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPanx(java.lang.String value) {
        this.panx = value;
    }

    /**
     * Gets the value of the pany property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPany() {
        return pany;
    }

    /**
     * Sets the value of the pany property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPany(java.lang.String value) {
        this.pany = value;
    }

    /**
     * Gets the value of the zoom property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getZoom() {
        return zoom;
    }

    /**
     * Sets the value of the zoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setZoom(java.lang.String value) {
        this.zoom = value;
    }

    /**
     * Gets the value of the decl property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDecl() {
        return decl;
    }

    /**
     * Sets the value of the decl property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDecl(java.lang.String value) {
        this.decl = value;
    }

}
